apiVersion: v1
kind: Pod
metadata:
  name: omnismart-pbx-api
  labels:
    app: pbx-api
    project: omnismart
    version: 1.0.0
spec:
  containers:
    - name: omnismart-pbx-api
      image: 724695599747.dkr.ecr.us-east-1.amazonaws.com/omni-pbx-api:latest